on:
#  schedule:
#    - cron: '0 5 * * *'
  workflow_dispatch:

env: 
  API_KEY: ${{ secrets.API_KEY }}
  APP_ID: ${{ secrets.APP_ID }}
  AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}

jobs:
  request-latest-tasks:
    runs-on: ubuntu-latest
    name: Update latest tasks
    steps:
      - name: checkout main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Retrieve tasks from server
        uses: isseikz/study-coding-gh-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          collection-name: simplified-commit
