on:
  push:
    branches:
      - main

env: 
  API_KEY: ${{ secrets.API_KEY }}
  APP_ID: ${{ secrets.APP_ID }}
  AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}

jobs:
  send-diff-to-service-job:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}
      - name: Create diff.patch from the latest commit
        id: create-diff
        run: echo "::set-output name=patch::${git diff HEAD^..DEAD}"
      - name: Send diff to our service
        uses: isseikz/send-pullrequests-info-gh-action@main
        with:
          diff: ${{ steps.create-diff.outputs.patch }}
  
