on:
  push:
    branches:
      - main

env: 
  API_KEY: ${{ secrets.API_KEY }}
  APP_ID: ${{ secrets.APP_ID }}
  AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}

jobs:
  send-diff-to-service-job:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 2
      - name: Create diff.patch from the latest commit
        id: create-diff
        run: |
          DIFF=$(git diff HEAD^..HEAD)
          SHA=$(git rev-parse HEAD^)
          echo "::set-output name=diff::$DIFF"
          echo "::set-output name=sha::$SHA"
          echo "GIT_DIFF<<EOF" >> $GITHUB_ENV
          echo "$DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Send diff to our service
        uses: isseikz/send-pullrequests-info-gh-action@main
        with:
          diff: ${{ env.GIT_DIFF }}
          sha: ${{ steps.create-diff.outputs.sha }}
          collection: 'answered-commit'
  
