on:
  pull_request:
    branches:
      - ${{ github.event.pull_request.base.ref }}
    types: [closed]
  workflow_dispatch: # testing use

env: 
  API_KEY: ${{ secrets.API_KEY }}
  APP_ID: ${{ secrets.APP_ID }}
  AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}

jobs:
  send-diff-to-service-job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Send diff to our service
        uses: isseikz/send-pullrequests-info-gh-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
